### ISSUE TITLE
Consider generating links.

### ISSUE THREAD

**Issue by kevincox** [SomebodyLikeEveryBody/ricochet_robot_map_formatter#2]
Hi, cool tool! I was considering writing something like this but I hadn't got around to it yet. I have one tip, it would be really cool if you could add a direct link to the game from the generator. https://ricochetrobots.kevincox.ca takes a `#s={board}` parameter that can be used to automatically fill in the generated board (ex: https://ricochetrobots.kevincox.ca/#s=EBAJIAEAEQQhAAEAQYAJAIELgQMJQAEBgQADEAEgAQRBAiEEASCBBAECCQABACEIgQOBBwUACUCBAAEgAQRBAIEICEHEY8PkwoVDSEHJwh3E3sEFDEBiKurcAg). The format isn't documented, but it is fairly easy. If you are interested I can help you implement it in javascript.

The code: [game](https://gitlab.com/kevincox/ricochetrobots/-/blob/df7a16af8d7941827d5d3a853ed1c5de2134d8d2/src/game.rs#L211-218), [board](https://gitlab.com/kevincox/ricochetrobots/-/blob/df7a16af8d7941827d5d3a853ed1c5de2134d8d2/src/board.rs#L224-250) and [target](https://gitlab.com/kevincox/ricochetrobots/-/blob/df7a16af8d7941827d5d3a853ed1c5de2134d8d2/src/target.rs#L26-31).

The format is a fairly simple byte-based encoding. The result is then base64 encoded to make it URL safe.

1. The width of the board as a byte. (always 16)
1. The height of the board as a byte. (always 16)
1. A bitstring of the horizontal walls (width*height/8 = 32 bytes)
1. A bitstring of the vertical walls (width*height/8 = 32 bytes)
1. The number of mirrors as a byte (I don't think you support mirrors right now so 0 would work).
1. The mirrors. (If none nothing).
1. The number of robots (always 5)
1. The robots as a single byte each. The high nibble is the x coordinate and the low nibble as the y coordinate.
1. The target.
  a. One byte for the position (same as robot location).
  b. One byte for [the colour](https://gitlab.com/kevincox/ricochetrobots/-/blob/df7a16af8d7941827d5d3a853ed1c5de2134d8d2/web/style.css#L7-11) or 0xFF for black.

Since it doesn't seem that you handle targets and robots you can just stick them in a fixed location and then they can be moved in the the solver UI.

Let me know what you think!

**Comment by SomebodyLikeEveryBody** [comment]
Great ! I will work on that an I keep you in touch
![cox](https://user-images.githubusercontent.com/48601663/89109736-45ac3600-d444-11ea-88a1-298f5a6d7d17.png)

**Comment by SomebodyLikeEveryBody** [comment]
Hello, Here is the new version: https://somebodylikeeverybody.github.io/Ricochet_Robot_map_formatter/

1) you choose the cell you want to change by clicking on it ==> cell catalogs appears. To make it disapear press ESCAPE
2) you press the key corresponding to the element you want to put on the cell:
UP for wall up, 
DOWN for wall down, 
LEFT for wall left, 
RIGHT for wall right, 
right SHIFT for no wall, 
Q for wall UPLEFT, 
A for DOWNLEFT, 
S for DOWNRIGHT, 
W for UPRIGHT

B for put blue robot
R for red robot
G for green robot
Y for yellow robot
D for grey robot

3) if you let the cell catalog open, when you move your mouse on the board, it will change the selection for the cell you have your mouse on ==> much easier to change multiples cells successively.

4) click on the buttons on the settings screen to see the code generated (I have to translate it to your pattern) or to go directly to your website (feature incoming ^^)

How do you find it ?

**Comment by kevincox** [comment]
I like it! However if you don't know the shortcuts it is very confusing. There is no way to close the menu for example which means I can't copy the code or click the go-to-solver link. Some ideas:

- Add a close button for the catalog.
- Change the letter on the robots and mirrors to match the shortcut key.
- Maybe put the shortcut key over the wall buttons as well?

> if you let the cell catalog open, when you move your mouse on the board, it will change the selection for the cell you have your mouse on ==> much easier to change multiples cells successively.

This is confusing because I clicked and moved the mouse over to select something in the catalog but this changed my "focus" to a cell by the wall. I was confused why the wrong cell was changing. There is also no visual indication of focus.

> 4. click on the buttons on the settings screen to see the code generated (I have to translate it to your pattern) or to go directly to your website (feature incoming ^^)

This is cool, I'm especially looking forward to the single-click transfer, it will be very convenient. However it appears that the code is no longer compatible with the solver website? Is there any reason for that? It seems we may as well keep them the same even if the link is the more convenient option.

It is looking very cool. I look forward to some more improvements.

**Comment by kevincox** [comment]
I've been using your site and it is working great. Shall we close this issue now?

**Comment by SomebodyLikeEveryBody** [comment]
Yes ! Thanks a lot !
